src/ZPB/Admin/MediatekBundle/Entity/Image.php
<?php

namespace ZPB\Admin\MediatekBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Image
 *
 * @ORM\Table(name="zpb_media_images")
 * @ORM\Entity(repositoryClass="ZPB\Admin\MediatekBundle\Entity\ImageRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Image
{
    /**
     * @var \Symfony\Component\HttpFoundation\File\UploadedFile
     * @Assert\Image(maxSize="6000000",mimeTypes ={"image/png","image/jpeg","image/gif"}, mimeTypesMessage="Votre image n'est pas une image valide.", maxSizeMessage="Votre image est trop lourde.")
     */
    public $file;
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    /**
     * @var string
     * @ORM\Column(name="filename", type="string", length=255)
     */
    private $filename;

    /**
     * @var string
     * @Assert\Regex("/^[a-zA-Z0-9._-]*$/", message="Ce champ contient des caractères non autorisés.")
     * @ORM\Column(name="name", type="string", length=255, nullable=true, unique=true)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="extension", type="string", length=255)
     */
    private $extension;

    /**
     * @var integer
     *
     * @ORM\Column(name="width", type="integer")
     */
    private $width;

    /**
     * @var integer
     *
     * @ORM\Column(name="height", type="integer")
     */
    private $height;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="createdAt", type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $createdAt;

    /**
     * @var string
     *
     * @ORM\Column(name="mime", type="string", length=255)
     */
    private $mime;

    /**
     * @var string
     * @ORM\Column(name="upload_dir", type="string", length=255, nullable=false)
     */
    private $uploadDir;

    /**
     * @var string
     * @ORM\Column(name="thumb_dir", type="string", length=255, nullable=false)
     */
    private $thumbDir;

    /**
     * @var string
     * @ORM\Column(name="copyright", type="string", length=255, nullable=true)
     * @Assert\Regex("/^[a-zA-Z0-9éèêëàûôç'.,@ _-]*$/", message="Ce champ contient des caractères non autorisés.")
     */
    private $copyright;
    /**
     * @var string
     * @ORM\Column(name="doc_root", type="string", length=255, nullable=false)
     */
    private $docRoot;

    /**
     * @var string
     * @ORM\Column(name="title", type="text", nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(name="is_article_thumbnail", type="boolean", nullable=false)
     */
    private $isArticleThumbnail;

    /**
     * @ORM\ManyToMany(targetEntity="ZPB\Admin\MediatekBundle\Entity\Tag", inversedBy="images")
     * @ORM\JoinTable(name="zpb_media_images_tags")
     */
    private $tags;

    private $originalPathForRemove;

    private $thumbPathForRemove;

    /**
     * @param string $uploadDir
     * @param string $thumbDir
     * @param string $docRoot
     * @param string $copyright
     */
    public function __construct($uploadDir = "uploads/medias/img", $thumbDir = 'uploads/medias/thumbs', $docRoot = "web", $copyright = "@ ZooParc de Beauval")
    {
        $this->tags = new ArrayCollection();
        $this->uploadDir = $uploadDir;
        $this->thumbDir = $thumbDir;
        $this->docRoot = $docRoot;
        $this->copyright = $copyright;
        $this->isArticleThumbnail = true;
    }

    /**
     * @ORM\PreRemove()
     */
    public function storePath()
    {
        $this->originalPathForRemove = $this->getAbsolutePath();
        $this->thumbPathForRemove = $this->getAbsoluteThumbnail();
    }

    /**
     * @ORM\PostRemove()
     */
    public function remove()
    {
        if($this->originalPathForRemove != null){
            unlink($this->originalPathForRemove);
        }
        if($this->thumbPathForRemove != null){
            unlink($this->thumbPathForRemove);
        }
    }

    /**
     * @return string
     */
    public function getThumbDir()
    {
        return $this->thumbDir;
    }

    /**
     * @param string $thumbDir
     */
    public function setThumbDir($thumbDir)
    {
        $this->thumbDir = $thumbDir;
    }

    /**
     * @return null|string
     */
    public function getWebPath()
    {
        return $this->filename === null ? null : "/" . $this->uploadDir . "/" . $this->filename;
    }

    /**
     * @return null|string
     */
    public function getWebThumbnail()
    {
        return $this->filename === null ? null : "/" . $this->thumbDir . "/" . $this->filename;
    }

    /**
     * @return null|string
     */
    public function getAbsoluteThumbnail()
    {
        return $this->filename === null ? null : $this->docRoot . "/" . $this->thumbDir . "/" . $this->filename;
    }

    /**
     * @return bool
     */
    public function upload()
    {
        if ($this->file == null) {
            return false;
        }
        $this->extension = $this->file->guessExtension();
        $this->mime = $this->file->getMimeType();
        $dest = $this->docRoot . "/" . $this->uploadDir;
        $this->filename = $this->name === null ? $this->sanitizeFilename($this->file->getClientOriginalName()) : $this->name . "." . $this->extension;
        if ($this->name === null) {
            $this->name = preg_replace('/\.(jpe?g|png|gif|JPE?G|PNG|GIF)$/', '', $this->filename);
        }
        $this->file->move($dest, $this->filename);
        $size = getimagesize($this->getAbsolutePath());
        $this->width = $size[0];
        $this->height = $size[1];
        $this->file = null;
        return true;
    }

    /**
     * @param string $string
     * @return string
     */
    private function sanitizeFilename($string="")
    {
        return preg_replace('/[^a-zA-Z0-9._-]/', '', $string);
    }

    public function getAbsolutePath()
    {
        return $this->filename === null ? null : $this->docRoot . "/" . $this->uploadDir . "/" . $this->filename;
    }

    /**
     * @return string
     */
    public function getDocRoot()
    {
        return $this->docRoot;
    }

    /**
     * @param string $docRoot
     */
    public function setDocRoot($docRoot)
    {
        $this->docRoot = $docRoot;
    }

    /**
     * @return string
     */
    public function getUploadDir()
    {
        return $this->uploadDir;
    }

    /**
     * @param string $uploadDir
     */
    public function setUploadDir($uploadDir)
    {
        $this->uploadDir = $uploadDir;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param $name
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get filename
     *
     * @return string
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * Set filename
     *
     * @param string $filename
     * @return Image
     */
    public function setFilename($filename)
    {
        $this->filename = $filename;

        return $this;
    }

    /**
     * Get extension
     *
     * @return string
     */
    public function getExtension()
    {
        return $this->extension;
    }

    /**
     * Set extension
     *
     * @param string $extension
     * @return Image
     */
    public function setExtension($extension)
    {
        $this->extension = $extension;

        return $this;
    }

    /**
     * Get width
     *
     * @return integer
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Set width
     *
     * @param integer $width
     * @return Image
     */
    public function setWidth($width)
    {
        $this->width = $width;

        return $this;
    }

    /**
     * Get height
     *
     * @return integer
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Set height
     *
     * @param integer $height
     * @return Image
     */
    public function setHeight($height)
    {
        $this->height = $height;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Image
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get mime
     *
     * @return string
     */
    public function getMime()
    {
        return $this->mime;
    }

    /**
     * Set mime
     *
     * @param string $mime
     * @return Image
     */
    public function setMime($mime)
    {
        $this->mime = $mime;

        return $this;
    }

    /**
     * Get copyright
     *
     * @return string
     */
    public function getCopyright()
    {
        return $this->copyright;
    }

    /**
     * Set copyright
     *
     * @param string $copyright
     * @return Image
     */
    public function setCopyright($copyright)
    {
        $this->copyright = $copyright;

        return $this;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Image
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param mixed $isArticleThumbnail
     */
    public function setIsArticleThumbnail($isArticleThumbnail)
    {

src/ZPB/Admin/MediatekBundle/Controller/ImageController.php
<?php
/**
 * Created by PhpStorm.
 * User: Nicolas Canfrère
 * Date: 06/08/14
 * Time: 14:46
 */
  /*
           ____________________
  __      /     ______         \
 {  \ ___/___ /       }         \
  {  /       / #      }          |
   {/ ô ô  ;       __}           |
   /          \__}    /  \       /\
<=(_    __<==/  |    /\___\     |  \
   (_ _(    |   |   |  |   |   /    #
    (_ (_   |   |   |  |   |   |
      (__<  |mm_|mm_|  |mm_|mm_|
*/

namespace ZPB\Admin\MediatekBundle\Controller;


use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use ZPB\Admin\CommonBundle\Controller\BaseController;
use ZPB\Admin\MediatekBundle\Entity\Image;
use ZPB\Admin\MediatekBundle\Form\Type\SimpleTagType;

class ImageController extends BaseController
{
    public function indexAction($page=1)
    {
        $images = $this->getRepo('ZPBAdminMediatekBundle:Image')->getAllImageAlphaOrdered($page, 10);
        $maxPage = $this->getRepo('ZPBAdminMediatekBundle:Image')->getNumPage(10);
        return $this->render('ZPBAdminMediatekBundle:Image:index.html.twig', ['images'=>$images, 'currentPage'=>$page, 'maxPage'=>$maxPage]);
    }

    public function newAction(Request $request)
    {
        $image = new Image(
            $this->container->getParameter('mediatek_uploads_img_dir'),
            $this->container->getParameter('mediatek_uploads_img_thumbs_dir'),
            $this->container->getParameter('mediatek_root_dir')
        );
        $form = $this->createFormBuilder($image)
            ->add('name')
            ->add('copyright')
            ->add('title',null,['label'=>'Attr. title'])
            ->add('file')
            ->add('tags', 'collection', ['label'=>'Mots-clés','type'=>new SimpleTagType(),'allow_add'=>true, 'by_reference'=>false])
            ->add('isArticleThumbnail',null, ['label'=>'Illustration d\'article ?'])
            ->add('save','submit')
            ->getForm();
        $form->handleRequest($request);
        if($form->isValid()){


            if($image->upload()){
                $em = $this->getEm();

                $tags = $image->getTags();
                foreach($tags as $tag){
                    $test = $this->getRepo('ZPBAdminMediatekBundle:Tag')->findOneByName($tag->getName());
                    if($test){
                        $image->removeTag($tag);
                        $image->addTag($test);
                        $test->addImage($image);
                        $em->persist($test);
                    } else {
                        $tag->addImage($image);
                        $em->persist($tag);
                    }
                }

                $em->persist($image);
                $em->flush();
                $resizer = $this->container->get('zpb.img_resizer');
                $resizer->resize($image);
                $this->successMessage('Votre image a bien été uploadée.');
                return $this->redirect($this->generateUrl('zpb_admin_mediatek_homepage'));
            }
            $this->errorMessage('Une erreur s\'est produite, votre image n\'a pas été traitée.');
            return $this->redirect($this->generateUrl('zpb_admin_mediatek_homepage'));
        }
        return $this->render('ZPBAdminMediatekBundle:Image:new.html.twig', ['form'=>$form->createView()]);
    }

    public function editAction($id, Request $request)
    {
        $csrfProv = $this->getCsrfProvider();
        $token = $request->query->get('_token', false);
        if(!$token || !$csrfProv->isCsrfTokenValid('image_edit',$token)){
            throw new AccessDeniedException();
        }
        $image = $this->getRepo('ZPBAdminMediatekBundle:Image')->find($id);
        if(!$image){
            throw $this->createNotFoundException();
        }
        $form = $this->createFormBuilder($image)
            ->add('name')
            ->add('title',null,['label'=>'Attr. title'])
            ->add('copyright')
            ->add('tags', 'collection', ['label'=>'Mots-clés','type'=>new SimpleTagType(),'allow_add'=>true, 'by_reference'=>false])
            ->add('isArticleThumbnail',null, ['label'=>'Illustration d\'article ?'])
            ->add('save','submit')
            ->getForm();
        ;
        $form->handleRequest($request);
        if($form->isValid()){
            $em = $this->getEm();
            $tags = $image->getTags();
            foreach($tags as $tag){
                $test = $this->getRepo('ZPBAdminMediatekBundle:Tag')->findOneByName($tag->getName());
                if($test){
                    $image->removeTag($tag);
                    $image->addTag($test);
                    $test->addImage($image);
                    $em->persist($test);
                } else {
                    $tag->addImage($image);
                    $em->persist($tag);
                }
            }
            $em->persist($image);
            $em->flush();
            $this->successMessage('Votre image a bien été mise à jour.');
            return $this->redirect($this->generateUrl('zpb_admin_mediatek_homepage'));
        }
        return $this->render('ZPBAdminMediatekBundle:Image:edit.html.twig', ['form'=>$form->createView(), 'image'=>$image]);
    }

    public function deleteAction($id, Request $request)
    {
        $csrfProv = $this->getCsrfProvider();
        $token = $request->query->get('_token', false);
        if(!$token || !$csrfProv->isCsrfTokenValid('image_delete',$token)){
            throw new AccessDeniedException();
        }
        $image = $this->getRepo('ZPBAdminMediatekBundle:Image')->find($id);
        if(!$image){
            throw $this->createNotFoundException();
        }


        $em = $this->getEm();
        $em->remove($image);
        $em->flush();


        $this->successMessage('Votre image a bien été supprimée.');
        return $this->redirect($this->generateUrl('zpb_admin_mediatek_homepage'));
    }
}

src/ZPB/Admin/MediatekBundle/Resources/views/Image/edit.html.twig
{% extends "ZPBAdminMediatekBundle:Layouts:master.html.twig" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <div class="h2">Images <small>Edition</small></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            {{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}
            {{ form_errors(form) }}
            <div class="form-group {% if form.name.vars.errors|length>0 %}has-error{% endif %}">
                {{ form_label(form.name) }}
                {{ form_widget(form.name, {"label": "Nom","attr":{"class":"form-control"}}) }}
                {{ form_errors(form.name) }}
            </div>
            <div class="form-group {% if form.copyright.vars.errors|length>0 %}has-error{% endif %}">
                {{ form_label(form.copyright) }}
                {{ form_widget(form.copyright, {"label": "Copyright","attr":{"class":"form-control"}}) }}
                {{ form_errors(form.copyright) }}
            </div>
            <div class="form-group {% if form.title.vars.errors|length>0 %}has-error{% endif %}">
                {{ form_label(form.title) }}
                {{ form_widget(form.title, {"attr":{"class":"form-control"}}) }}
                {{ form_errors(form.title) }}
            </div>
            <div class="form-group">
                {{ form_label(form.tags) }}
                {{ form_widget(form.tags) }}
                <div class="tags" data-prototype="{{ form_widget(form.tags.vars.prototype)|e }}"></div>
                {{ form_errors(form.tags) }}
            </div>
            <div class="checkbox">
                {{ form_widget(form.isArticleThumbnail, {"attr":{"style":"margin-left:0;"}}) }}{{ form_label(form.isArticleThumbnail) }}
                {{ form_errors(form.isArticleThumbnail) }}
            </div>
            <div class="form-group">
                {{ form_widget(form.save, {"label": "Mettre à jour", "attr":{"class":"btn btn-primary"}}) }}
            </div>
            {{ form_end(form) }}
        </div>
        <div class="col-md-8">
            <a href="{{ image.webPath }}" target="_blank"><img src="{{ image.webThumbnail }}" title="{{ image.title }} {{ image.copyright|raw }}" class="img-thumbnail"/></a>
        </div>
    </div>

{% endblock %}
{% block footScripts %}
    {{ parent() }}
    <script>
        var collectionHolder = $('div.tags');
        var protoHolder = $("#form_tags");
        var $addTagLink = $('<a href="#" class="add_tag_link btn btn-default">Ajouter un mot-clé</a>');
        var $newLinkLi = $('<div class="form-group"></div>').append($addTagLink);
        function addTagForm(collectionHolder, $newLinkLi) {
            var prototype = protoHolder.attr('data-prototype');
            var newForm = prototype.replace(/<label class=\"required\">__name__label__<\/label>/g, "");
            newForm = newForm.replace(/__name__/g, (collectionHolder.children().length + protoHolder.children().length));
            var nf = $(newForm);
            var label = nf.find("label");
            var ipt = nf.find("input");
            var parent = label.parent();
            parent.addClass("form-group");
            ipt.addClass("form-control");
            collectionHolder.append(nf);
        }
        if(protoHolder.children().length){
            protoHolder.children().each(function(idx,el){
                var fLabel = $(el).find("label:first");
                fLabel.remove();
                var sLabel = $(el).find("label");
                var parent = sLabel.parent();
                parent.addClass("form-group");
                var ipt = parent.find("input");
                ipt.addClass("form-control");
            });
        }
        collectionHolder.after($newLinkLi);
        $addTagLink.on('click', function(e) {
            e.preventDefault();
            addTagForm(collectionHolder, $newLinkLi);
        });
    </script>
{% endblock %}

src/ZPB/Admin/MediatekBundle/Resources/views/Image/index.html.twig
{% extends "ZPBAdminMediatekBundle:Layouts:master.html.twig" %}

{% set active_ss_menu = "all_img" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <div class="h2">Images <small>Liste</small></div>
            </div>
        </div>
    </div>
    {% if maxPage > 1 %}
        <div class="col-md-12 text-center">
            <ul class="pagination">
                {% if currentPage == 1 %}
                    <li class="disabled"><a href="#">&laquo;</a></li>
                {% else %}
                    <li><a href="{{ path("zpb_admin_mediatek_homepage", {page:1}) }}">&laquo;</a></li>
                {% endif %}
                {% for p in 1..maxPage %}
                    {% if p==currentPage %}
                        <li class="disabled"><a href="#">{{ p }}</a></li>
                    {% else %}
                        <li><a href="{{ path("zpb_admin_mediatek_homepage", {page:p}) }}">{{ p }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if currentPage == maxPage %}
                    <li class="disabled"><a href="#">&raquo;</a></li>
                {% else %}
                    <li><a href="{{ path("zpb_admin_mediatek_homepage", {page:maxPage}) }}">&raquo;</a></li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-hover table-striped">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Vignette</th>
                        <th>Nom du fichier</th>
                        <th>Copyright</th>
                        <th>Contenu de l'attr. title</th>
                        <th>Largeur originale</th>
                        <th>Hauteur originale</th>
                        <th>Mots-clés</th>
                        <th>Editer</th>
                        <th>Supprimer</th>
                    </tr>
                    </thead>
                    <tbody>
                    {%  if images|length < 1 %}
                        <tr class="warning">
                            <td colspan="9">Il n'y a aucune image dans la bibliothèque commune. <a
                                        href="{{ path("zpb_admin_mediatek_new") }}">Upload <i class="fa fa-hand-o-right"></i></a></td>
                        </tr>
                    {% else %}
                        {% for img in images %}
                        <tr>
                            <td>{{ img.id }}</td>
                            <td><a href="{{ img.webPath }}" target="_blank"><img src="{{ img.webThumbnail }}" title="{{ img.title }} {{ img.copyright|raw }}" width="50"/></a></td>
                            <td>{{ img.filename }}</td>
                            <td>{{ img.copyright }}</td>
                            <td>{{ img.title }}</td>
                            <td>{{ img.width }}</td>
                            <td>{{ img.height }}</td>
                            <td>
                                {% if img.tags|length <1 %} - {% else %}{% for tag in img.tags %}<a href="{{ path("zpb_admin_mediatek_tag_assoc_img", {id: tag.id, _token: csrf_token("tag_assoc_img")})}}">{{ tag.name}}</a> {% if loop.last != true %} - {% endif %}{% endfor %}{% endif %}
                            </td>
                            <td><a class="btn btn-default" href="{{ path("zpb_admin_mediatek_edit", {id: img.id, _token: csrf_token("image_edit")}) }}"><i class="fa fa-edit"></i></a></td>
                            <td><a href="{{ path("zpb_admin_mediatek_delete", {id: img.id, _token: csrf_token("image_delete")} )}}" class="btn btn-default delete-alert" data-name="{{ img.name }}"><i class="fa fa-trash-o"></i></a></td>{# TODO #}
                        </tr>
                        {% endfor %}
                    {% endif %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}
{% block footScripts %}
    {{ parent() }}
    <script>
        $(function(){
            $(".delete-alert").on("click", function(e){
                e.preventDefault();
                var name = $(this).data("name");
                if(window.confirm("Attention, cette action est irréversible, êtes-vous certain de vouloir continuer et effacer '" + name + "' ?")){
                    window.location.href = $(this).attr("href");
                }
            });
        });
    </script>

{% endblock %}

src/ZPB/Admin/MediatekBundle/Resources/views/Image/new.html.twig
{% extends "ZPBAdminMediatekBundle:Layouts:master.html.twig" %}

{% set active_ss_menu = "new_img" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <div class="h2">Images <small>Upload</small></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            {{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}
            {{ form_errors(form) }}
            <div class="form-group {% if form.name.vars.errors|length>0 %}has-error{% endif %}">
                {{ form_label(form.name) }}
                {{ form_widget(form.name, {"label": "Nom","attr":{"class":"form-control"}}) }}
                {{ form_errors(form.name) }}
            </div>
            <div class="form-group {% if form.copyright.vars.errors|length>0 %}has-error{% endif %}">
                {{ form_label(form.copyright) }}
                {{ form_widget(form.copyright, {"label": "Copyright","attr":{"class":"form-control"}}) }}
                {{ form_errors(form.copyright) }}
            </div>
            <div class="form-group {% if form.title.vars.errors|length>0 %}has-error{% endif %}">
                {{ form_label(form.title) }}
                {{ form_widget(form.title, {"attr":{"class":"form-control"}}) }}
                {{ form_errors(form.title) }}
            </div>
            <div class="form-group {% if form.file.vars.errors|length>0 %}has-error{% endif %}">
                {{ form_label(form.file) }}
                {{ form_widget(form.file, {"label": "Fichier"}) }}
                {{ form_errors(form.file) }}
            </div>
            <div class="form-group">
                {{ form_label(form.tags) }}
                {{ form_widget(form.tags) }}
                <div class="tags" data-prototype="{{ form_widget(form.tags.vars.prototype)|e }}"></div>
                {{ form_errors(form.tags) }}
            </div>
            <div class="checkbox">
                {{ form_widget(form.isArticleThumbnail, {"attr":{"style":"margin-left:0;"}}) }}{{ form_label(form.isArticleThumbnail) }}
                {{ form_errors(form.isArticleThumbnail) }}
            </div>
            <div class="form-group">
                {{ form_widget(form.save, {"label": "Upload", "attr":{"class":"btn btn-primary"}}) }}
            </div>
            {{ form_end(form) }}
        </div>
        <div class="col-md-8"></div>
    </div>
{% endblock %}

{% block footScripts %}
    {{ parent() }}
    <script>
        var collectionHolder = $('div.tags');
        var protoHolder = $("#form_tags");
        var $addTagLink = $('<a href="#" class="add_tag_link btn btn-default">Ajouter un mot-clé</a>');
        var $newLinkLi = $('<div class="form-group"></div>').append($addTagLink);
        function addTagForm(collectionHolder, $newLinkLi) {
            var prototype = protoHolder.attr('data-prototype');
            var newForm = prototype.replace(/<label class=\"required\">__name__label__<\/label>/g, "");
            newForm = newForm.replace(/__name__/g, (collectionHolder.children().length + protoHolder.children().length));
            var nf = $(newForm);
            var label = nf.find("label");
            var ipt = nf.find("input");
            var parent = label.parent();
            parent.addClass("form-group");
            ipt.addClass("form-control");
            collectionHolder.append(nf);
        }
        if(protoHolder.children().length){
            protoHolder.children().each(function(idx,el){
                var fLabel = $(el).find("label:first");
                fLabel.remove();
                var sLabel = $(el).find("label");
                var parent = sLabel.parent();
                parent.addClass("form-group");
                var ipt = parent.find("input");
                ipt.addClass("form-control");
            });
        }
        collectionHolder.after($newLinkLi);
        $addTagLink.on('click', function(e) {
            e.preventDefault();
            addTagForm(collectionHolder, $newLinkLi);
        });
    </script>
{% endblock %}